create table khlystov_currencycourses
(
    ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CODE varchar(50) NOT NULL,
    DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COURSE float NOT NULL,
    PRIMARY KEY (ID)
)